
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.facebook.fbreact.specs;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeSystemVpnSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "SystemVpn";

  public NativeSystemVpnSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void prepare(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void connect(ReadableMap config, String address, String username, String password, String secret, boolean disconnectOnSleep, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void saveConfig(ReadableMap config, String address, String username, String password, String secret, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getCurrentState(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getCharonErrorState(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getConnectionTimeSecond(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void disconnect(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void clearKeychainRefs(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void addListener(String eventName);

  @ReactMethod
  @DoNotStrip
  public abstract void removeListeners(double count);
}
